export { default as STableLayout } from './STableLayout.vue';
// export { default as STable } from './STable.vue';
// export { default as STableHead } from './STableHead.vue';
export { default as STableHeadItem } from './STableHeadItem.vue';
// export { default as STableBody } from './STableBody.vue';
// export { default as STableRow } from './STableRow.vue';
export { default as STableRowItem } from './STableRowItem.vue';
export { default as STablePagination } from './STablePagination.vue';
export { default as SServerTable } from './SServerTable.vue';
// export { default as SDataTable } from './SDataTable.vue';
