name: "publish"

on:
  push:
    branches:
      - main
jobs:
  release:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm ci
      - run: npm run build
      - run: npm publish --access=public
