name: 'test'
on:
    workflow_dispatch:
jobs:
    release:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Set release type output
              id: release-type
              run: |
                  USER_INPUT=${{ github.event.inputs.release-type }}
                  echo "RELEASE_TYPE=${USER_INPUT:-"prerelease"}" >> $GITHUB_OUTPUT

            - name: checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: npm ci && npm t

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
